export const DISHES_LOADING="DISHES_LOADING";
export const DISHES_FAILED="DISHES_FAILED";
export const ADD_DISHES="ADD_DISHES";

export const COMMENTS_lOADING="COMMENTS_LOADING";
export const COMMENTS_FAILED="COMMENTS_FAILED";
export const ADD_COMMENTS="ADD_COMMENTS";
export const ADD_COMMENT="ADD_COMMENT";

export const LEADERS_lOADING="LEADERS_lOADING";
export const LEADERS_FAILED="LEADERS_FAILED";
export const ADD_LEADERS="ADD_LEADERS";

export const PROMOTIONS_lOADING="PROMOTIONS_lOADING";
export const PROMOTIONS_FAILED="PROMOTIONS_FAILED";
export const ADD_PROMOTIONS="ADD_PROMOTIONS";
